
# Show sensitive information for endpoints:
#endpoints:
#  sensative : true;

# Security for endpoints:
#management:
#  security:
#    enabled: false

# Disable BASIC Authentication:
#security:
#  basic:
#    enabled: false
#  user:
#    name: user1
#    password: changeme
